openapi: 3.0.0
info:
  title: Inspiration API
  description: |
    API for generating quotes to motivate or inspire.
    
    The API uses a cache, which expires every hour so quotes do not get updated in this period.
  version: 1.0.0
servers:
  - url: https://api.goprogram.ai
paths:
  /inspiration:
    get:
      summary: Get an inspirational quote
      description: Get an inspirational quote
      operationId: getQuote
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  quote:
                    type: string
                    description: The text of the quote
                  author:
                    type: string
                    description: The name of the author of the quote
      tags:
        - inspiration
