openapi: 3.0.0
info:
  title: JC Quotes API
  description: API to generate a random quote from James Clear
  version: 1.0.0
servers:
  - url: https://www.jcquotes.com
paths:
  /api/quotes/random:
    get:
      summary: Returns a random quote from James Clear
      description: Returns a random quote from James Clear
      operationId: getRandomQuote
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  source:
                    type: string
                    description: The source URL of the quote
                  clickToTweetId:
                    type: string
                    description: The click-to-tweet ID of the quote
                  rawText:
                    type: string
                    description: The raw text of the quote, including the author's Twitter handle
                  text:
                    type: string
                    description: The text of the quote, without the author's Twitter handle
                    example: How can I improve the energy of the situations I am involved in today?\nYou may not control the outcome, but you can influence it.
