openapi: 3.0.0
info:
  title: Mailcheck.ai API
  version: 1.0.0
  description: Check if a domain has valid MX records and if it is disposable
servers:
  - url: https://api.mailcheck.ai
paths:
  /domain/{domain}:
    get:
      summary: Check a domain
      parameters:
        - name: domain
          in: path
          description: The domain to check, example gmail.com
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  domain:
                    type: string
                  mx:
                    type: boolean
                  disposable:
                    type: boolean
                  did_you_mean:
                    type: string
                    nullable: true
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  error:
                    type: string
        "429":
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  error:
                    type: string

  /email/{email}:
    get:
      summary: Check an email
      parameters:
        - name: email
          in: path
          description: The email to check, example test@mail7.io
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  email:
                    type: string
                  domain:
                    type: string
                  mx:
                    type: boolean
                  disposable:
                    type: boolean
                  alias:
                    type: boolean
                  did_you_mean:
                    type: string
                    nullable: true
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  error:
                    type: string
        "429":
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  error:
                    type: string
