openapi: 3.0.0
info:
  title: Metaphorpsum API
  description: |
    Get paragraphs or sentences of metaphorical text by sending an AJAX request.
    For getting response without the <p> tag, do not send the parameter
    
  version: 1.0.0
servers:
  - url: http://metaphorpsum.com
paths:
  /paragraphs/{numberOfParagraphs}:
    get:
      summary: Get paragraphs of metaphorical text
      description: Get paragraphs of metaphorical text
      operationId: getParagraphs
      parameters:
        - name: numberOfParagraphs
          in: path
          description: The number of paragraphs to return (max 20).
          required: true
          schema:
            type: integer
            maximum: 20
            example: 3
        - name: p
          in: query
          description: Set to 'true' to wrap each paragraph in <p> tags.
          required: false
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /paragraphs/{numberOfParagraphs}/{numberOfSentences}:
    get:
      summary: Get paragraphs of metaphorical text with specific number of sentences
      description: Get paragraphs of metaphorical text
      operationId: getParagraphsWithSentences
      parameters:
        - name: numberOfParagraphs
          in: path
          description: The number of paragraphs to return (max 20).
          required: true
          schema:
            type: integer
            maximum: 20
            example: 3
        - name: numberOfSentences
          in: path
          description: The number of sentences per paragraph to return (max 50).
          required: true
          schema:
            type: integer
            maximum: 50
            example: 2
        - name: p
          in: query
          description: Set to 'true' to wrap each paragraph in <p> tags.
          required: false
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /sentences/{numberOfSentences}:
    get:
      summary: Get sentences of metaphorical text
      description: Get sentences of metaphorical text
      operationId: getSentences
      parameters:
        - name: numberOfSentences
          in: path
          description: The number of sentences to return (max 50).
          required: true
          schema:
            type: integer
            maximum: 50
            example: 3
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
