openapi: 3.0.0
info:
  title: PingUtil Email Validation API
  version: 1.0.0
  description: API to validate email addresses
servers:
  - url: http://api.eva.pingutil.com
paths:
  /email:
    get:
      summary: Validate email address
      description: Validate email address
      operationId: validateEmail
      parameters:
        - name: email
          in: query
          description: Email address to validate, example test@mail7.io
          required: true
          schema:
            type: string
            format: email
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                    description: Indicates whether the email address is valid
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "429":
          description: Too Many Requests
        "500":
          description: Internal Server Error
