openapi: 3.0.0
info:
  title: Shibe.online API
  version: 1.0.0
  description: |
    Shibe.online is an API for getting images of shibes, cats, and birds.
    Shibes are common dogs in Japan (Shiba Inu).

    Common parameters in the API - 

      1. httpsUrls - Defaults to HTTPs
      2. urls - Defaults to true
servers:
  - url: https://shibe.online/api
paths:
  /shibes:
    get:
      summary: Get images of shibes
      description: Returns a list of random images of shibes.
      operationId: getShibeImages
      parameters:
        - name: count
          in: query
          description: The number of images to be returned.
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
        - name: urls
          in: query
          description: Should the API return URLs or filenames without extensions?
          required: false
          schema:
            type: boolean
        - name: httpsUrls
          in: query
          description: Should the URLs be HTTPS or HTTP?
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: A list of image URLs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /cats:
    get:
      summary: Get images of cats
      description: Returns a list of random images of cats.
      operationId: getCatImages
      parameters:
        - name: count
          in: query
          description: The number of images to be returned.
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
        - name: urls
          in: query
          description: Should the API return URLs or filenames without extensions?
          required: false
          schema:
            type: boolean
        - name: httpsUrls
          in: query
          description: Should the URLs be HTTPS or HTTP?
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: A list of image URLs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /birds:
    get:
      summary: Get images of birds
      description: Returns a list of random images of birds.
      operationId: getBirdImages
      parameters:
        - name: count
          in: query
          description: The number of images to be returned.
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
        - name: urls
          in: query
          description: Should the API return URLs or filenames without extensions?
          required: false
          schema:
            type: boolean
        - name: httpsUrls
          in: query
          description: Should the URLs be HTTPS or HTTP?
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: A list of image URLs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
